### ISSUE TITLE
Write access to this repo

### ISSUE THREAD

**Issue by 130s** [ros-gbp/ar_track_alvar-release#1]
As per https://github.com/sniekum/ar_track_alvar/issues/41 could someone give a write access to @130s?

**Comment by 130s** [comment]
@sniekum

**Comment by sniekum** [comment]
Done.

**Comment by 130s** [comment]
Thanks, I now see I can write to https://github.com/sniekum/ar_track_alvar. Just making sure but in order to release I also need a write access to this repo. Anyway I'll try bloom when things are ready, and ask again if I don't have a right yet.

**Comment by 130s** [comment]
I meant this repo as in ros-gbp/ar_track_alvar-release, not sniekum/ar_track_alvar

**Comment by 130s** [comment]
I'm afraid I might not have a write access to https://github.com/ros-gbp/ar_track_alvar-release/ yet. bloom failed like below. Maybe @wjwwood can help me out?

```
$ bloom-release --rosdistro jade --track jade ar_track_alvar
:
See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': 130s
Password for 'https://130s@github.com': 
remote: Permission to ros-gbp/ar_track_alvar-release.git denied to 130s.
fatal: unable to access 'https://github.com/ros-gbp/ar_track_alvar-release.git/': The requested URL returned error: 403
Cannot push to remote release repository.
```

**Comment by wjwwood** [comment]
Should be done.
